### PR TITLE
Fixes #6 - added selection nodes with getting a selection

### LINKED ISSUE #6: Expose start and end nodes
Right after getting and setting a selection I am finding that I need to get the selection nodes.  It would be much easier to just expose them from here instead of me having to re-get the selection.  If this is something you are interested in I will put together a PR for it.  Let me know!

### PR DESCRIPTION
**Pull request by wesleytodd**
Should work, but I didn't run the tests (see #8).  Basically just what we talked about in #6

### CODE REVIEW

**Comment by wesleytodd** [comment]
I guess since this didn't get merged there are now conflicts.  Is there still interest in this feature?  If so I will update the PR.

**Comment by bmcmahen** [comment]
Doh, sorry! I just got back from travelling for a couple of months. And updated PR would be nice.

**Comment by wesleytodd** [comment]
Updated, looks like we both added a new test at the bottom.

**Comment by bmcmahen** [comment]
Thanks!

**Comment by wesleytodd** [comment]
NP! Glad I could contribute :)

**Pull request merged**
